;===============================================================================
; CockpitInjectables.ahk - Per-instance injectable account counters
;===============================================================================
; Source of truth: `Accounts\Saved\<N>\list_current.txt`, generated by
; `carddb.exe schedule-accounts` (rerun every ~60 min or when queue <= 1).
;
; This module only counts scheduler output. It does not
; re-implement the filter logic of the scheduler.
;
; Fallback chain when list_current.txt is missing or empty:
;   1. list.txt       (the full pre-scheduled list)
;   2. raw XML count  (filtered by simple pack-prefix only; APPROX)
;
; Cache: results are cached for `CACHE_TTL_S` seconds. Aggregator can override
; by calling Injectables_InvalidateCache().
;===============================================================================

global INJECTABLES_CACHE_TTL_S := 10
global g_injCacheEpoch := 0
global g_injCacheMode  := ""
global g_injCacheData  := ""
global g_injCacheSource := ""

Injectables_InvalidateCache() {
    global g_injCacheEpoch := 0
}

;-------------------------------------------------------------------------------
; Injectables_GetAll(instances, mode)
;   instances : configured count (e.g. 8)
;   mode      : the current deleteMethod (e.g. "Inject Wonderpick 96P+")
;
; Returns: { total: N, perInstance: {1:n1, 2:n2, ...}, source: "list_current|list|raw" }
;-------------------------------------------------------------------------------
Injectables_GetAll(instances, mode) {
    global g_injCacheEpoch, g_injCacheMode, g_injCacheData, g_injCacheSource

    now := CockpitState_NowEpoch()
    if (g_injCacheEpoch > 0 && g_injCacheMode = mode
        && (now - g_injCacheEpoch) < INJECTABLES_CACHE_TTL_S) {
        return g_injCacheData
    }

    result := { "total": 0, "perInstance": {}, "source": "raw" }

    Loop, % instances {
        instanceNum := A_Index
        info := Injectables_ForInstance(instanceNum, mode)
        result.perInstance[instanceNum] := info["count"]
        result.total += info["count"]
        ; Keep the least authoritative source across instances.
        if (Injectables_SourceWeight(info["source"]) < Injectables_SourceWeight(result.source)
            || result.source = "raw")
            result.source := info["source"]
    }

    g_injCacheEpoch := now
    g_injCacheMode  := mode
    g_injCacheData  := result
    return result
}

Injectables_SourceWeight(source) {
    if (source = "list_current") return 3
    if (source = "list")         return 2
    if (source = "raw")          return 1
    return 0
}

;-------------------------------------------------------------------------------
; Injectables_ForInstance(instance, mode)
;   Returns: { count: N, source: "list_current|list|raw", path: "..." }
;-------------------------------------------------------------------------------
Injectables_ForInstance(instance, mode) {
    base := getScriptBaseFolder() . "\Accounts\Saved\" . instance
    res  := { "count": 0, "source": "", "path": "" }

    if (!FileExist(base)) {
        res.source := "list_current"  ; missing folder = empty queue, authoritative
        return res
    }

    pathCurrent := base . "\list_current.txt"
    if (FileExist(pathCurrent)) {
        res.count  := Injectables_CountNonEmptyLines(pathCurrent)
        res.source := "list_current"
        res.path   := pathCurrent
        return res
    }

    pathList := base . "\list.txt"
    if (FileExist(pathList)) {
        res.count  := Injectables_CountNonEmptyLines(pathList)
        res.source := "list"
        res.path   := pathList
        return res
    }

    ; Fallback: raw XML count with a simple pack-prefix filter
    minPacks := Injectables_MinPacksForMode(mode)
    res.count  := Injectables_CountRawXml(base, minPacks)
    res.source := "raw"
    res.path   := base
    return res
}

Injectables_CountNonEmptyLines(path) {
    count := 0
    if (!FileExist(path))
        return 0
    FileRead, content, %path%
    if (content = "")
        return 0
    Loop, Parse, content, `n, `r
    {
        line := Trim(A_LoopField)
        if (line = "")
            continue
        if (StrLen(line) < 5)
            continue
        count++
    }
    return count
}

Injectables_CountRawXml(dir, minPacks) {
    count := 0
    Loop, Files, %dir%\*.xml
    {
        ; AHK Loop, Files gives filename in A_LoopFileName
        fn := A_LoopFileName
        if (minPacks = -1)
            continue
        if (RegExMatch(fn, "^(\d+)P_\d+_\d+\([BT]+\)\.xml$", m)) {
            if ((m1 + 0) >= minPacks)
                count++
        }
    }
    return count
}

Injectables_MinPacksForMode(mode) {
    if (mode = "Inject Wonderpick 96P+")
        return 96
    if (mode = "Inject 13P+")
        return 13
    if (mode = "Inject Rewards")
        return 0
    if (mode = "Create Bots (13P)")
        return -1   ; no target / N/A
    return 0
}

;-------------------------------------------------------------------------------
; Optional: per-mode breakdown (used by Cockpit standalone preview)
;   Returns { "Inject Wonderpick 96P+": {total, perInstance{}}, ... }
;-------------------------------------------------------------------------------
Injectables_AllByMode(instances) {
    modes := ["Inject Wonderpick 96P+", "Inject 13P+", "Inject Rewards", "Create Bots (13P)"]
    out := {}
    for _, m in modes {
        out[m] := Injectables_GetAllUncached(instances, m)
    }
    return out
}

; Uncached variant used by AllByMode (we don't want to thrash the single-mode cache)
Injectables_GetAllUncached(instances, mode) {
    result := { "total": 0, "perInstance": {}, "source": "raw" }
    Loop, % instances {
        instanceNum := A_Index
        info := Injectables_ForInstance(instanceNum, mode)
        result.perInstance[instanceNum] := info["count"]
        result.total += info["count"]
    }
    return result
}
